#!/usr/bin/env node

var exec = require('child_process').exec;
var root = ".";
var main = process.argv[2];

var command = 'java -jar ' + __dirname + '/fermat.jar ' + root + ' ' + main;
console.log(command)

var child = exec(command, function(err, stdout, stderr) {
  if (err === null) {
    console.log('stdout: ' + stdout);
    console.log('stderr: ' + stderr)
  } else {
    console.log(err);
    console.log(err.code);
    console.log(err.signal);
  }
})